flavors:
  # persistent disks
  - name: core-100
    kind: persistent-disk
    cost:
      - { key: "persistent-disk", value: 1.0, unit: "COUNT" }
      - { key: "persistent-disk.flavor.core-100", value: 1.0, unit: "COUNT" }
      - { key: "persistent-disk.cost", value: 1.0, unit: "COUNT" }

  - name: core-200
    kind: persistent-disk
    cost:
      - { key: "persistent-disk", value: 1.0, unit: "COUNT" }
      - { key: "persistent-disk.flavor.core-200", value: 1.0, unit: "COUNT" }
      - { key: "persistent-disk.cost", value: 1.8, unit: "COUNT" }

  - name: core-300
    kind: persistent-disk
    cost:
      - { key: "persistent-disk", value: 1.0, unit: "COUNT" }
      - { key: "persistent-disk.flavor.core-300", value: 1.0, unit: "COUNT" }
      - { key: "persistent-disk.cost", value: 2.8, unit: "COUNT" }
